using Namotion.Reflection;
using NJsonSchema;
using NJsonSchema.Generation;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Nodes;
using Lib.Json;
using Newtonsoft.Json;
using UfoGameLib.Model;

// using Swashbuckle.AspNetCore.SwaggerGen;
using UfoGameLib.State;
using YamlDotNet.Serialization.NodeDeserializers;
using JsonIgnoreAttribute = System.Text.Json.Serialization.JsonIgnoreAttribute;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace UfoGameLib.Api;

// kja generated "Assets" and "Agent" schema is empty for http endpoints but works for https.
// Both for localhost and Azure.
/// <summary>
/// This schema filter ensures that OpenAPI schema generated from C# classes is generated properly.
/// This means following transformations:
///
/// - Ensure the schema includes the same fields and properties as determined by
/// UfoGameLib.State.GameState.StateJsonSerializerOptions.
/// Specifically, it includes fields and excludes members with [JsonIgnore] attribute.
///
/// - Ensure each property is included once, capitalized. This means removing not-capitalized
/// properties. E.g. removing "id" when "Id" is present.
///
/// - Strip inheritors of List, like Agents or Missions, from the extra properties generated by default.
/// </summary>
// https://github.com/RicoSuter/NJsonSchema/wiki/Schema-Processors
// ReSharper disable once ClassNeverInstantiated.Global
// Reason: used in Program / builder.Services.AddSwaggerGen / opts.SchemaFilter<...this class...>();
public class GameStateNSwagSchemaProcessor : ISchemaProcessor
{
    private readonly HashSet<Type> _processedTypes = new HashSet<Type>();

    public void Process(SchemaProcessorContext context)
    {
        ContextualType type = context.ContextualType;

        if (!_processedTypes.Add(type))
            return;

        Console.Out.WriteLine($"===== Processing {type.Name}");

        if (type.Name == nameof(GameState))
        {
            // Console.Out.WriteLine($"gen settings: {context.Generator.Settings.ToIndentedUnsafeJsonString()}");
        }

        JsonSchema schema = context.Schema;

        if (type.Name == nameof(GameState))
            schema.Example =
                "You can obtain example GameState JSON by calling appropriate " +
                "API route that returns initial GameState.";

        // foreach ((string? key, JsonSchemaProperty? value) in schema.Properties)
        // {
        //     Console.Out.WriteLine($"Schema prop: {key}: {value.Name}");
        // }

        MemberInfo[] members = type.Type.GetMembers(BindingFlags.Public | BindingFlags.Instance);

        if (type.Name == nameof(Assets))
        {
            // https://github.com/RicoSuter/NJsonSchema#njsonschema-usage
            string json = schema.ToJson();
            Console.Out.WriteLine("Original assets schema: " + schema.ToJson());
            Console.Out.WriteLine("Parsing node from json");
            JsonNode node = JsonNode.Parse(json)!;
            JsonSchemaProperty prop = new JsonSchemaProperty
            {
                Type = JsonObjectType.Integer,
                Description = "Money",
                Example = 1000
            };

            node["properties"] = new JsonObject
            {
                ["Money"] = new JsonObject
                {
                    ["type"] = "integer",
                    ["description"] = "Money",
                    ["example"] = 1000
                }
            };
            schema = JsonSchema.FromJsonAsync(node.ToJsonString()).GetAwaiter().GetResult();
            Console.Out.WriteLine("Modified assets schema: " + schema.ToJson());
            //context.Resolver.AddSchema(typeof(Assets), false, schema);

        }

        // if (type.Name == nameof(Assets))
        // {
        //     List<FieldInfo> fieldInfos = members.Where(member => member is FieldInfo fi).Cast<FieldInfo>().ToList();
        //
        //     FieldInfo fieldInfo = fieldInfos.Single(fi => fi.Name.Contains("Money"));
        //
        //     Console.Out.WriteLine($"Field Info: {fieldInfo.FieldType} {fieldInfo.Name}");
        //
        //     Console.Out.WriteLine("Generating: " + fieldInfo.FieldType);
        //     JsonSchema generatedSchema = context.Generator.Generate(fieldInfo.FieldType, context.Resolver);
        //     Console.Out.WriteLine("generatedSchema: " + generatedSchema.ToJson());
        //
        //
        //     // https://github.com/RicoSuter/NJsonSchema/issues/1326#issuecomment-784937686
        //     Console.Out.WriteLine("Adding schema: " + fieldInfo.FieldType);
        //     context.Resolver.AddSchema(fieldInfo.FieldType, false, generatedSchema);
        //     foreach (JsonSchema resolverSchema in context.Resolver.Schemas)
        //     {
        //         Console.Out.WriteLine("Schema in resolver: " + resolverSchema.ToJson(Formatting.Indented));
        //     }
        //     //JsonSchema jsonSchema = context.Resolver.GetSchema(fieldInfo.FieldType, false);
        //     
        //     Console.Out.WriteLine("Converting to prop: " + fieldInfo.Name);
        //     var prop = JsonSerializer.Deserialize<JsonSchemaProperty>(generatedSchema.ToJson())!;
        //     schema.Properties[fieldInfo.Name] = prop;
        //
        //     Console.Out.WriteLine("Assets schema: " + schema.ToJson());
        // }
        //
        // if (type.Name == nameof(GameState))
        // {
        //     List<FieldInfo> fieldInfos = members.Where(member => member is FieldInfo fi).Cast<FieldInfo>().ToList();
        //
        //     FieldInfo fieldInfo = fieldInfos.Single(fi => fi.Name.Contains("Assets"));
        //
        //     Console.Out.WriteLine($"Field Info: {fieldInfo.FieldType} {fieldInfo.Name}");
        //
        //
        //     context.Generator.Generate(fieldInfo.FieldType, context.Resolver);
        //     
        //     // https://github.com/RicoSuter/NJsonSchema/issues/1326#issuecomment-784937686
        //     JsonSchema jsonSchema = context.Resolver.GetSchema(fieldInfo.FieldType, false);
        //     var prop = JsonSerializer.Deserialize<JsonSchemaProperty>(jsonSchema.ToJson())!;
        //     schema.Properties[fieldInfo.Name] = prop;
        //
        //     // WORKS
        //     // JsonSchema agentJsonSchema = JsonSchema.FromType<Agent>();
        //     // string jsonStr = agentJsonSchema.ToJson();
        //     // var prop = JsonSerializer.Deserialize<JsonSchemaProperty>(jsonStr)!;
        //     // schema.Properties["TestAgent"] = prop;
        //
        //     Console.Out.WriteLine("GameState schema: " + schema.ToJson());
        // }

        // if (type.Name != nameof(GameState))
        // {
        //     Console.Out.WriteLine("Bailing early!");
        //     return;
        // }

        // foreach (ContextualPropertyInfo ctxProp in type.Properties)
        // {
        //     Console.Out.WriteLine($"ctxProp: {ctxProp.PropertyType}.{ctxProp.Name}");
        // }
        //
        // foreach (ContextualFieldInfo ctxField in type.Fields)
        // {
        //     Console.Out.WriteLine($"ctxField: {ctxField.FieldType}.{ctxField.Name}");
        // }
        //
        // foreach (MemberInfo member in members)
        // {
        //     if (member is PropertyInfo propertyInfo)
        //         Console.Out.WriteLine($"Member Prop {member.DeclaringType}.{member.Name}");
        //     if (member is FieldInfo fieldInfo)
        //         Console.Out.WriteLine($"Member Field {member.DeclaringType}.{member.Name}");
        // }

        //
        // foreach (MemberInfo member in members)
        // {
        //     // Skip members with [JsonIgnore] attribute
        //     if (IsJsonIgnore(member))
        //         continue;
        //
        //     // Include public properties and public fields.
        //     if (member is PropertyInfo propertyInfo)
        //     {
        //         //JsonSchema jsonSchema = context.Generator.Generate(propertyInfo.PropertyType);
        //         Console.Out.WriteLine($"Processing Prop {type}.{member.Name}");
        //         //schema.Properties[propertyInfo.Name] = (JsonSchemaProperty)jsonSchema;
        //         // schema.Properties[propertyInfo.Name] = context.Generator.Generate(
        //         //     propertyInfo.PropertyType,
        //         //     context.SchemaRepository);
        //
        //         RemoveLowerCasedKey(schema, propertyInfo);
        //     }
        //     else if (member is FieldInfo fieldInfo)
        //     {
        //         // Console.Out.WriteLine($"Processing Field {type}.{member.Name}");
        //         // schema.Properties[fieldInfo.Name] = context.SchemaGenerator.GenerateSchema(
        //         //     fieldInfo.FieldType,
        //         //     context.SchemaRepository);
        //
        //         RemoveLowerCasedKey(schema, fieldInfo);
        //     }
        //     else
        //     {
        //         // Do not include other member kinds.
        //         if (schema.Properties.ContainsKey(member.Name))
        //         {
        //             // Console.Out.WriteLine($"Removed other {type}.{member.Name}");
        //             schema.Properties.Remove(member.Name);
        //         }
        //     }
        // }
        //
        // StripListInheritorsOfExtraProps(schema, type);
    }

    private static bool IsJsonIgnore(MemberInfo member)
        => member.GetCustomAttribute<JsonIgnoreAttribute>() != null;

    private static void RemoveLowerCasedKey(JsonSchema schema, MemberInfo memberInfo)
    {
        string nameWithLower = ToLowerFirstChar(memberInfo.Name);
        if (schema.Properties.ContainsKey(nameWithLower))
        {
            // Console.Out.WriteLine($"Removed lower {memberInfo.DeclaringType}.{memberInfo.Name}");
            schema.Properties.Remove(nameWithLower);
        }
    }

    private static string ToLowerFirstChar(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        return char.ToLower(input[0]) + input[1..];
    }

    private static void StripListInheritorsOfExtraProps(JsonSchema schema, Type type)
    {
        if (IsSubclassOfGenericType(type, genericType: typeof(List<>)))
        {
            // Console.WriteLine($"Stripping {type.FullName} of extra properties.");
            schema.Properties.Clear();
        }
    }

    private static bool IsSubclassOfGenericType(Type? typeToCheck, Type genericType)
    {
        // Check if the typeToCheck is a class and not an interface or abstract class.
        if (typeToCheck is { IsClass: true, IsGenericTypeDefinition: false })
        {
            while (typeToCheck != null)
            {
                if (typeToCheck.IsGenericType && typeToCheck.GetGenericTypeDefinition() == genericType)
                {
                    return true;
                }

                typeToCheck = typeToCheck.BaseType;
            }
        }

        return false;
    }
}